### ISSUE TITLE
[Koa] Unblock application startup

### ISSUE THREAD

**Issue by okoala** [Glimpse/Home#100]
Koa is very awesome，so i want you to support it.

**Comment by davidkpiano** [comment]
There are no current official plans to support Koa, but having support for other popular Node.JS frameworks, such as Hapi and Koa, is definitely within consideration in the future. At the very least, we would like to provide basic insights for any Node.JS framework (such as capturing `http` calls, etc.).

What deep insights would you like to see in Koa?

**Comment by philliphoff** [comment]
[Some changes are in the pipeline](#95) to make Glimpse work better with non-Express frameworks, to at least capture some basic information, even while those frameworks may not be officially supported.  Those changes appear to play nice with both Hapi and Koa (at least in trivial apps).  

We'll let you know when they're available and, by all means, let us know if Glimpse works in your application!

**Comment by hardchor** [comment]
Koa support would be awesome, most of my private (and apps at work) use it. We're quite a sizeable team of node developers, and people seem to really like it

**Comment by avanderhoorn** [comment]
We just released a fix to npm in glimpse version v0.20.9 that addresses this issue. If you're still having problems w/ koa, please let us know!

Note, this release doesn't include any specific insights into Koa itself, but I'd be interested to know what Koa specific insights you would like to see and what priority you would put on them if you had $100 to spend on getting them done - @hardchor @okoala 

Thanks!

**Comment by burkhardr** [comment]
Managed to get it running, thanks for that! http://node.getglimpse.com/docs/setup/getting-started/#how-do-i-manually-inject-the-abbr-title-heads-up-display-hud-abbr-and-browser-agent-into-my-site helped in getting the HUD working as well.

I've yet to try it out on a frontend app, but at first glance, the obvious one missing is support for koa middleware.

**Comment by avanderhoorn** [comment]
@burkhardr Middleware is what I suspected would come up, anything else? Also we have a fix coming in the next release which should remove the need for any manual registration of HUD or the browser agent (except in cases where the front end is being served from non node processes - like a CDN). Did you also include the browser agent in your registration? That could explain some of the missing data... you should see everything except the middleware table filling out correctly (note some of the detailed network timing is only available for browser requests).

**Comment by burkhardr** [comment]
Yes, I did include both snippets from the docs.

I just managed to test it out on a frontend app, and all the functionality (apart from middleware support) seems to be there. Nice tool!

**Comment by nikmd23** [comment]
Hi @burkhardr and/or @hardchor! 😉 

We'd also love to have a chat with you about how you're using Glimpse, what's useful and what isn't. It shouldn't take more than 30 mins and there's no need to prepare in advance. If you're interested, just pick a time slot over at https://calendly.com/nikmd23/30min

Thanks!

**Comment by hardchor** [comment]
@nikmd23 I've already had a chat with @avanderhoorn a few weeks ago 😃
