### ISSUE TITLE
[Loopback] support

### ISSUE THREAD

**Issue by NilsFrkal** [Glimpse/Home#112]
I tried to run glimpse together with Loopback framework. The client cannot establish a connection. It would be great if loopback support could be enabled. Best, Nils

**Comment by philliphoff** [comment]
Thanks for the feedback @NilsFrkal!  While we don't specifically support LoopBack, I agree that it would be great if Glimpse at least played nice with it.  

I was able to identify a couple of issues related to how LoopBack dynamically registers middleware as well as how Glimpse deals with compressed (e.g. `gzip` encoded) responses that result in errors when using Glimpse with LoopBack.  I've submitted a PR with fixes that should go into an upcoming release.  I'll let you know when it's out so you can try it.  

Also, is there anything specifically related to LoopBack (as opposed to Express or Node.js) that you wish Glimpse would provide insights for?

**Comment by NilsFrkal** [comment]
@philliphoff thanks a lot for the fast response. At this stage I would not have any loopback specific feedback. Once the standard glimpse functionality is enabled and I can start testing I will be more than happy to provide additional feedback.

**Comment by avanderhoorn** [comment]
It looks like we have a solution and are currently doing some testing to make sure we have gotten all the edge cases we can see. Hopefully this will get in the upcoming release. We will let you know how testing goes! Thanks again.

**Comment by mike-kaufman** [comment]
verified build v021.3 works against this app: https://github.com/strongloop/loopback-getting-started.  Note that HUD isn't showing up because the response is compressed - we're tracking that with a seperate issue.

This will be available on npm in a few days.

**Comment by mike-kaufman** [comment]
Fix for this is availabe on NPM now with glimpse version 0.21.5.

**Comment by nikmd23** [comment]
Hi @NilsFrkal!

We'd love to have a chat with you about how you're using Glimpse, what's useful and what isn't. It shouldn't take more than 30 mins and there's no need to prepare in advance. If you're interested, just pick a time slot over at https://calendly.com/nikmd23/30min

Thanks!
