### ISSUE TITLE
Glimpse (Warning OlderUnsupportedPackageRequired): Glimpse does not support version 2.3.3 of debug.

### ISSUE THREAD

**Issue by julianfrank** [Glimpse/Home#116]
I'm getting the error 
```
Glimpse (Warning OlderUnsupportedPackageRequired): Glimpse does not support version 2.3.3 of debug. You can get rich insights into  debug by upgrading to a supported version, as covered at https://github.com/Glimpse/Home#package--version-support.
```
The URL unfortunately has no help on what needs to be done...

What am I supposed to do when this error happens?

**Comment by mike-kaufman** [comment]
Hey @julianfrank - can you update to version 2.6.x of Debug?  We have proxies for it, but we haven't verified it on older versions.  

Thanks for reporting this.  We'll fix up the error message here so it is more actionable.

**Comment by nikmd23** [comment]
Also, on a side note @julianfrank, we'd love to have a chat with you about how you're using Glimpse, what's useful and what isn't. It shouldn't take more than 30 mins and there's no need to prepare in advance. If you're interested, just pick a time slot over at https://calendly.com/nikmd23/30min

Thanks!

**Comment by mike-kaufman** [comment]
Glimpse release 0.22.x (coming soon) will support Debug versions 2.0 through 2.7 inclusive, and will fix up the docs around this error.

**Comment by mike-kaufman** [comment]
The 0.22.11 release is available on npm now.  Release notes are here: http://node.getglimpse.com/updates/v0_22.11/
