### ISSUE TITLE
Deep link to https://github.com/Glimpse/Home#package--version-support is broken

### ISSUE THREAD

**Issue by mike-kaufman** [Glimpse/Home#117]
When someone uses a module that is older/newer than what our proxies are tested against, we spit out an warning (see #116).  The deep link URL is broken.  Need to do the following:

  - [ ] Move the "supported version" info into node.getglimpse.com.
  - [ ] update the URL.

**Comment by avanderhoorn** [comment]
@mike-kaufman please verify fix.
