### ISSUE TITLE
Use Glimpse with separate frontend and backend procceses?

### ISSUE THREAD

**Issue by dj-hedgehog** [Glimpse/Home#121]
I would like to use Glimpse for multiple projects. There are 2 different setups:

1. frontend served (mainly) statically via Express app which reverse proxies request to the backend (Express.js node process).

2. frontend served statically via Nginx reverse proxying requests to the backend (Express.js node process)

Is it possible to use Glimpse with this setup at all? In case 1 it would only contain data from the frontend and the (boring) static Express server. However I want data included from the real backend.

**Comment by mike-kaufman** [comment]
Hi @dj-hedgehog - 

For 1), check out the write-up [here](http://node.getglimpse.com/docs/user-guide/glimpse-architecture/#multiple-processes-sharing-a-single-glimpse-server), which explains how to set glimpse to work across multiple node processes.  The end result is in when you look at the glimpse UI, you'll be able to see details for requests into both your front-end & backend. 

For 2), you can run glimpse solely on your back-end.  You won't be able to see the our heads-up-display (HUD).  You can, however, go to `http://<your-backend-node-server>:<port>/glimpse/client`, and you'll see the full glimpse UI for all requests into your backend. 

Let us know if you have any more questions or need clarification on any of the above.

Thanks,

Mike

**Comment by avanderhoorn** [comment]
@dj-hedgehog please do let us know how you go. We are very keen to see how people fine this setup and any feedback you may have. So please let us know when you have a chance to try it out!

**Comment by mike-kaufman** [comment]
Closing this out.  Please reactivate if you're not unblocked.  :)
