### ISSUE TITLE
[Home repo]: update screenshot to reflect current UIs

### ISSUE THREAD

**Issue by mike-kaufman** [Glimpse/Home#124]
@legomushroom commented on [Thu Jun 29 2017](https://github.com/Glimpse/Glimpse.Client/issues/1382)

Screenshot in `Readme.md` is deprecated, update it.

**Comment by legomushroom** [comment]
The `Home` repo uses the `Hero1` image from the website, but since the image has cache-busting hash in its name(e.g. `Hero1.93802.svg`), we just have to make sure the link to the image will still be working(in case the hash will change).
