### ISSUE TITLE
[Response] The Connection and Date response headers aren't being displayed

### ISSUE THREAD

**Issue by lostintangent** [Glimpse/Home#17]
**Repro Steps:**
1. Generate a request for a document (it might impact AJAX requests as well, but I didn't test that)
2. Within the Glimpse client, select the request entry you just generated
3. Look at the response headers

**Expected:** To see a `Connection` and `Date` header, which confirmed in both Chrome DevTools are Fiddler are actually present present.

![fiddler](https://cloud.githubusercontent.com/assets/116461/18561329/420e82cc-7b34-11e6-9f2c-673d52410f39.PNG)

**Actual:** Every request and response header is correctly displayed, except for the `Connection` and `Date` response headers.

![glimpseresponse](https://cloud.githubusercontent.com/assets/116461/18561333/44490774-7b34-11e6-81e9-02a49b4590e6.PNG)

This is a pretty low-priority bug from my perspective, but I was confused when I didn't see these headers in Glimpse, and so I jumped to other tools to confirm. When I had worked on the F12 network tool, we had a lot of customers that would "cross check" us against Chrome and Fiddler to gain confidence in the data, so these kinds of mismatches can be meaningful sometimes to try to address.

**Environment:**
- Node 5.1.1
- Express 4.13.4 (I'm assuming this is a reasonably new version?)

**Comment by davidkpiano** [comment]
Confirmed:
<img width="583" alt="screen shot 2017-05-25 at 5 29 15 pm" src="https://cloud.githubusercontent.com/assets/1093738/26471478/dc28c01e-416f-11e7-9f07-3d6610f9e47b.png">

**Comment by mike-kaufman** [comment]
Fix for this is availabe on NPM now with glimpse version 0.21.5.
