### ISSUE TITLE
[Client] Request list doesn't appear populated in IE/Edge

### ISSUE THREAD

**Issue by lostintangent** [Glimpse/Home#21]
**Repro steps:**
1. Open up the Glimpse client in IE or Edge

**Expected:** To see the list of requests
**Actual:** The client UI appears, but the request list is empty

The client works perfectly in Chrome, so the issue appears to be limited to IE/Edge. When I open up the dev tools, there is an error in the console, so maybe the databinding logic doesn't work currently in IE/Edge?

![error](https://cloud.githubusercontent.com/assets/116461/18562543/03a7381c-7b39-11e6-8c97-55cf0fa64e4d.PNG).

**Comment by mike-kaufman** [comment]
Closing this,  Been fixed a while & we don't support IE 11.
