### ISSUE TITLE
HUD not working for repos that don't use Express

### ISSUE THREAD

**Issue by jasonyueyang** [Glimpse/Home#70]
Today we rely on Express to inject the HUD script. For projects that don't use Express, HUD doesn't work.

One example of such project is https://github.com/pencilblue/pencilblue (https://pencilblue.org/), a content management system and blogging platform for Node.js. 

To support this, we might need to use lower level APIs to inject the script tag.

**Comment by nikmd23** [comment]
This is now supported with manual injection. The process is documented at http://node.getglimpse.com/docs/setup/getting-started/#how-do-i-manually-inject-the-abbr-title-heads-up-display-hud-abbr-and-browser-agent-into-my-site
