### ISSUE TITLE
Website and API in different projects

### ISSUE THREAD

**Issue by christophersw** [Glimpse/Home#94]
Our [team](https://www.shieldmyfiles.com/team/) would like to use glimpse on a [big project](https://app.shieldmyfiles.com) we are working on, but are facing some confusion on how to get it up and running... The challenge stems from the fact that we separate our front-end website and our backend APIs into individual projects (NPM packages) managed as individual repositories. We do this to make them easier to work with, deploy, and scale independently. 

We host the following projects, each on their own dedicated domain:

- SPA (AngularJS, Express)
- Main API (Express)
- Accounts API (Express)

We would like to use Glimpse on the SPA, but still be able to view the services running on in our API projects.

Any guidance on how/if this could be achieved would be really helpful. 

Before installing and deploying Glimpse all over our stack, I figured I would ask here first to see if anybody has done this before. 

Thanks, 
Chris

**Comment by mike-kaufman** [comment]
@christophersw  - we have a fix for this now in NPM.  I'm going to close this issue.  Please let us know if you have any more problems.
