### ISSUE TITLE
[Typescript] Definitions

### ISSUE THREAD

**Issue by atrauzzi** [Glimpse/Home#96]
Added the new nodejs edition of glimpse, but didn't get any type information for my TS based project.  Would love to see some added along with the project so that my imports are strongly typed!

**Comment by avanderhoorn** [comment]
Great point. Are you thinking predominantly for the config options that we provide?

**Comment by atrauzzi** [comment]
Yeah, at the very least.  I don't know if there's more beyond that, but so long as that's there, I can incorporate it as part of my framework when it's run on browsers.

**Comment by avanderhoorn** [comment]
The next release we put out (which should be in the next few days) will have the fix for this.

**Comment by mike-kaufman** [comment]
We just released v0.20.9 to npm.  This build includes the basic set of typescript definitions  (we'll have more as we expand out our public API, but we're not there just yet... :) ). 

Thanks for reporting this. Please let us know if what you have any problems trying out the latest release.

**Comment by atrauzzi** [comment]
Thanks!
